apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pharma-db-secrets
  namespace: dev
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: db-credentials-k8s
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: pharma/dev/db-credentials
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pharma-jwt-secret
  namespace: dev
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: jwt-secret-k8s
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: /pharma/dev/jwt-secret
