name: Reusable Node.js CI/CD

on:
  workflow_call:
    inputs:
      service-name:
        required: true
        type: string
      service-path:
        required: true
        type: string
    secrets:
      AWS_GITHUB_ACTIONS_ROLE_ARN:
        required: true
      HELM_CHARTS_TOKEN:
        required: true
      HELM_CHARTS_REPO:
        required: true

env:
  AWS_REGION: us-east-1
  ECR_REGISTRY: 579378699469.dkr.ecr.us-east-1.amazonaws.com

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install and Test
        run: |
          cd ${{ inputs.service-path }}
          npm ci
          npm test --if-present

  docker-build-push:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    permissions:
      id-token: write
      contents: read
    outputs:
      image-tag: ${{ steps.meta.outputs.tag }}
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_GITHUB_ACTIONS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set image tag
        id: meta
        run: echo "tag=${GITHUB_SHA::8}" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        run: |
          cd ${{ inputs.service-path }}
          docker build -t ${{ env.ECR_REGISTRY }}/${{ inputs.service-name }}:${{ steps.meta.outputs.tag }} .
          docker push ${{ env.ECR_REGISTRY }}/${{ inputs.service-name }}:${{ steps.meta.outputs.tag }}

  deploy:
    needs: docker-build-push
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - name: Determine environment
        id: env
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "env=prod" >> $GITHUB_OUTPUT
          elif [[ "${{ github.ref }}" == "refs/heads/develop" ]]; then
            echo "env=qa" >> $GITHUB_OUTPUT
          else
            echo "env=dev" >> $GITHUB_OUTPUT
          fi

      - name: Clone helm-charts repo
        run: |
          git clone https://x-access-token:${{ secrets.HELM_CHARTS_TOKEN }}@github.com/sarat2729/pharmops-gitops.git

      - name: Update image tag
        run: |
          cd pharmops-gitops
          FILE="envs/${{ steps.env.outputs.env }}/values-${{ inputs.service-name }}.yaml"
          sed -i "s/tag: .*/tag: \"${{ needs.docker-build-push.outputs.image-tag }}\"/" $FILE
          git config user.email "github-actions@github.com"
          git config user.name "GitHub Actions"
          git add .
          git commit -m "chore: update ${{ inputs.service-name }} image tag to ${{ needs.docker-build-push.outputs.image-tag }} [skip ci]"
          git push
