name: "CI/CD - Auth Service"

on:
  push:
    branches: [main, develop, "feature/**", "bugfix/**", "hotfix/**"]
    paths:
      - "services/auth-service/**"
      - ".github/workflows/ci-auth-service.yml"
  pull_request:
    branches: [main, develop]
    paths:
      - "services/auth-service/**"

permissions:
  id-token: write
  contents: read

jobs:
  ci-cd:
    uses: ./.github/workflows/_reusable-springboot.yml
    with:
      service-name: auth-service
      service-path: services/auth-service
    secrets: inherit
